routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('adminlogin')->name('adminlogin.')->namespace('School')->group(function(){
    Route::name('index')->get('/','AdminController@showLogin');
    Route::name('login')->post('login','AdminController@login');
    Route::name('logout')->get('logout','AdminController@logout');
});

Route::group(['middleware'=>'admin'],function (){
    Route::prefix('admin')->name('admin.')->namespace('School')->group(function(){
        Route::name('index')->get('/','AdminController@index');
        Route::name('create')->post('create','AdminController@create');
        Route::name('edit')->post('{id}/edit','AdminController@update');
        Route::name('delete')->get('{id}/delete','AdminController@delete');
    });
    Route::prefix('year')->name('year.')->namespace('School')->group(function (){
        Route::name('index')->get('/','YearController@index');
        Route::name('create')->post('create','YearController@create');
        Route::name('edit')->post('{id}/edit','YearController@update');
        Route::name('delete')->get('{id}/delete','YearController@delete');
    });
    Route::prefix('batch')->name('batch.')->namespace('School')->group(function (){
        Route::name('index')->get('/','BatchController@index');
        Route::name('create')->post('create','BatchController@create');
        Route::name('edit')->post('{id}/edit','BatchController@update');
        Route::name('delete')->get('{id}/delete','BatchController@delete');
    });
    Route::prefix('major')->name('major.')->namespace('School')->group(function (){
        Route::name('index')->get('/','MajorController@index');
        Route::name('create')->post('create','MajorController@create');
        Route::name('edit')->post('{id}/edit','MajorController@update');
        Route::name('delete')->get('{id}/delete','MajorController@delete');
    });
    Route::prefix('exam')->name('exam.')->namespace('School')->group(function (){
        Route::name('index')->get('/','ExamController@index');
        Route::name('create')->post('create','ExamController@create');
        Route::name('edit')->post('{id}/edit','ExamController@update');
        Route::name('delete')->get('{id}/delete','ExamController@delete');
    });
    Route::prefix('category')->name('category.')->namespace('School')->group(function(){
        Route::name('index')->get('/','CategoryController@index');
        Route::name('create')->post('create','CategoryController@create');
        Route::name('edit')->post('{id}/edit','CategoryController@update');
        Route::name('delete')->get('{id}/delete','CategoryController@delete');
    });
    Route::prefix('subject')->name('subject.')->namespace('School')->group(function (){
        Route::name('index')->get('/','SubjectController@index');
        Route::name('create')->post('create','SubjectController@create');
        Route::name('edit')->post('{id}/edit','SubjectController@update');
        Route::name('delete')->get('{id}/delete','SubjectController@delete');
    });
    Route::prefix('student')->name('student.')->namespace('School')->group(function (){
        Route::name('index')->get('/','StudentController@index');
        Route::name('create')->post('create','StudentController@create');
        Route::name('edit')->post('{id}/edit','StudentController@update');
        Route::name('delete')->get('{id}/delete','StudentController@delete');
        Route::name('detail')->get('{id}/detail','MarkController@detail');
        Route::name('card')->get('{id}/card','StudentController@getcard');
        Route::name('excel')->post('excel','ExcelController@getexcel');
        Route::name('search')->post('search','StudentController@search');
    });
    Route::prefix('mark')->name('mark.')->namespace('School')->group(function(){
        Route::name('index')->get('/','MarkController@index');
        Route::name('create')->post('create','MarkController@create');
        Route::name('edit')->post('{id}/edit','MarkController@update');
        Route::name('delete')->get('{id}/delete','MarkController@delete');
    });
    Route::prefix('excel')->name('excel.')->namespace('School')->group(function(){
        Route::name('downloadExcel')->post('downloadExcel', 'MaatwebsiteController@downloadExcel');
    });
    Route::prefix('pdf')->name('pdf.')->namespace('School')->group(function (){
        Route::name('downloadPdf')->post('{id}/downloadPdf','PdfController@getPdf');
    });
    Route::get('/getimages/{image}','School\StudentController@getImage');
});

resources/views/admin/create_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_addadmin">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Admin</h4>
                </div>

                <form method="post" action="{{route('admin.create')}}">
                    {{csrf_field()}}
                    <div class="for-year">
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Name</label>
                            <input type="text" class="name-input" id="name" name="name" value="{{old('name')}}">
                            @if($errors->has('name'))
                                <span class="error">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Email</label>
                            <input type="text" class="name-input" id="name" name="email" value="{{old('email')}}">
                            @if($errors->has('email'))
                                <span class="error">{{$errors->first('email')}}</span>
                            @endif
                        </div>
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Password</label>
                            <input type="text" class="name-input" id="name" name="password" value="{{old('password')}}">
                            @if($errors->has('password'))
                                <span class="error">{{$errors->first('password')}}</span>
                            @endif
                        </div>
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Confirm Password</label>
                            <input type="text" class="name-input" id="name" name="password_confirmation" value="{{old('password_confirmation')}}">
                            @if($errors->has('password_confirmation'))
                                <span class="error">{{$errors->first('password_confirmation')}}</span>
                            @endif
                        </div>

                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/admin/delete_modal.blade.php
<div class="modal fade" id="modal_deleteadmin" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content modal-logout">
            <div class="modal-header">
                <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Are You Sure?</h4>
            </div>
            <form id="deleteurl">
                <div class="logout-modal">
                    <!-- <div class="modal-footerdelete"> -->
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel
                    </button>
                    <button type="submit" class="btn btn-primary">Ok</button>
                    <!-- </div> -->
                </div>
            </form>
        </div>

    </div>
</div>

resources/views/admin/edit_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_editadmin">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Admin</h4>
                </div>

                <form method="post" id="editurl">
                    {{csrf_field()}}
                    <div class="for-year">
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Name</label>
                            <input type="text" class="name-input" id="admin_name" name="name">
                            @if($errors->has('name'))
                                <span class="error">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Email</label>
                            <input type="text" class="name-input" id="admin_email" name="email">
                            @if($errors->has('email'))
                                <span class="error">{{$errors->first('email')}}</span>
                            @endif
                        </div>

                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/admin/index.blade.php
@extends('masteradmin')
@section('title','Admin')
@section('content')

    <div class="list-of-class">
        <p>List of Admins</p>
    </div>

    <div class="main-content">
        {{--<div class="select-class">--}}
        {{--<label>Select Class Name</label>--}}
        {{--<select>--}}
        {{--<option>Standard-1</option>--}}
        {{--<option>Standard-2</option>--}}
        {{--<option>Standard-3</option>--}}
        {{--<option>Standard-4</option>--}}
        {{--</select>--}}
        {{--</div>--}}

        {{--<div class="show-entries">--}}
        {{--<label>Show</label>--}}
        {{--<select>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--<option>10</option>--}}
        {{--</select>--}}
        {{--</div>--}}

        <div class="add-student">
            <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_addadmin">
                <i class="fa fa-plus"></i>&nbspAdd Admin
            </button>
        </div>

        {{--<div class="dropdown print">--}}
        {{--<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-print"></i>Print--}}
        {{--<span class="caret"></span></button>--}}
        {{--<ul class="dropdown-menu printdropdown">--}}
        {{--<li><a href="#">A4</a></li>--}}
        {{--<li><a href="#">A5</a></li>--}}
        {{--<li><a href="#">A6</a></li>--}}
        {{--</ul>--}}
        {{--</div>--}}

        {{--<div class="search-box">--}}
        {{--<label>Search</label>--}}
        {{--<input class="search">--}}
        {{--</div>--}}

        <table class="table-bordered table-striped table">
            <tr>
                {{--<th><input type="checkbox"></input></th>--}}
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th>
                    {{--<select>--}}
                    {{--<option>Select Action</option>--}}
                    {{--<option>Select</option>--}}
                    {{--<option>Select</option>--}}
                    {{--<option>Select</option>--}}
                    {{--</select>--}}
                </th>
            </tr>
            @php($no=1)
                @foreach($admins as $admin)
                    <tr>
                        {{--<td><input type="checkbox"></td>--}}
                        <td>{{$no++}}</td>
                        <td>{{$admin->name}}</td>
                        <td>{{$admin->email}}</td>
                        <td>
                            <button class="delete" data-toggle="modal" data-target="#modal_deleteadmin" data-deleteurl="{{route('admin.delete',['id'=>$admin->id])}}"><i class="fa fa-trash-o"></i></button>
                            <button class="edit" data-toggle="modal" data-target="#modal_editadmin" data-admin="{{$admin}}" data-editurl="{{route('admin.edit',['id'=>$admin->id])}}"><i class="fa fa-pencil"></i></button>
                        </td>
                    </tr>
                @endforeach

        </table>

        {{--<p>Showing 1 to 10 of 17 entries</p>--}}

        {{--<div class="page">--}}
        {{--<ul class="pagination">--}}
        {{--<li class="page-item"><a class="page-link" href="#">Previous</a></li>--}}
        {{--<li class="page-item"><a class="page-link" href="#">1</a></li>--}}
        {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
        {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
        {{--<li class="page-item"><a class="page-link" href="#">Next</a></li>--}}
        {{--</ul>--}}
        {{--</div>--}}
    </div>
@endsection
@section('models')
    @include('admin.create_modal')
    @include('admin.edit_modal')
    @include('admin.delete_modal')
@endsection
@section('script')
    <script src="{{asset('js/admin.js')}}"></script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap-datepicker.css">

    <link href="https://fonts.googleapis.com/css?family=Oswald:300" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css">
</head>
<body>
<div class="login-form">
    <form method="post" action="{{route('adminlogin.login')}}">
        {{csrf_field()}}
        <h3>Login</h3>

        <div class="login-footer">
            <span></span>
            <div class="login-control">
                <input type="text" class="login-box" id="email" placeholder="Email" name="email" value="{{old('name')}}">
                @if($errors->has('email'))
                    <span class="error">{{$errors->first('email')}}</span>
                @endif
            </div>

            <div class="login-control">
                <input type="password" class="login-box" id="password" placeholder="Password" name="password" value="{{old('password')}}">
                @if($errors->has('password'))
                    <span class="error">{{$errors->first('password')}}</span>
                    @endif
            </div>

            <div class="login-control">
                <button>Login</button>
            </div>
        </div>
        <p><a href="#"></a></p>
    </form>
</div>
</body>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>

resources/views/admin/logout_modal.blade.php
<div class="modal fade" id="Logout_Modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content modal-logout">
            <div class="modal-header">
                <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Are You Sure?</h4>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span> -->
            </div>
            <form action="{{route('adminlogin.logout')}}">
            <div class="logout-modal">
                <!-- <div class="modal-footerdelete"> -->
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel
                </button>
                <button type="submit" class="btn btn-primary">Ok</button>
                <!-- </div> -->
            </div>
            </form>
        </div>

    </div>
</div>