routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('adminlogin')->name('adminlogin.')->namespace('School')->group(function(){
    Route::name('index')->get('/','AdminController@showLogin');
    Route::name('login')->post('login','AdminController@login');
    Route::name('logout')->get('logout','AdminController@logout');
});

Route::group(['middleware'=>'admin'],function (){
    Route::prefix('admin')->name('admin.')->namespace('School')->group(function(){
        Route::name('index')->get('/','AdminController@index');
        Route::name('create')->post('create','AdminController@create');
        Route::name('edit')->post('{id}/edit','AdminController@update');
        Route::name('delete')->get('{id}/delete','AdminController@delete');
    });
    Route::prefix('year')->name('year.')->namespace('School')->group(function (){
        Route::name('index')->get('/','YearController@index');
        Route::name('create')->post('create','YearController@create');
        Route::name('edit')->post('{id}/edit','YearController@update');
        Route::name('delete')->get('{id}/delete','YearController@delete');
    });
    Route::prefix('batch')->name('batch.')->namespace('School')->group(function (){
        Route::name('index')->get('/','BatchController@index');
        Route::name('create')->post('create','BatchController@create');
        Route::name('edit')->post('{id}/edit','BatchController@update');
        Route::name('delete')->get('{id}/delete','BatchController@delete');
    });
    Route::prefix('major')->name('major.')->namespace('School')->group(function (){
        Route::name('index')->get('/','MajorController@index');
        Route::name('create')->post('create','MajorController@create');
        Route::name('edit')->post('{id}/edit','MajorController@update');
        Route::name('delete')->get('{id}/delete','MajorController@delete');
    });
    Route::prefix('exam')->name('exam.')->namespace('School')->group(function (){
        Route::name('index')->get('/','ExamController@index');
        Route::name('create')->post('create','ExamController@create');
        Route::name('edit')->post('{id}/edit','ExamController@update');
        Route::name('delete')->get('{id}/delete','ExamController@delete');
    });
    Route::prefix('category')->name('category.')->namespace('School')->group(function(){
        Route::name('index')->get('/','CategoryController@index');
        Route::name('create')->post('create','CategoryController@create');
        Route::name('edit')->post('{id}/edit','CategoryController@update');
        Route::name('delete')->get('{id}/delete','CategoryController@delete');
    });
    Route::prefix('subject')->name('subject.')->namespace('School')->group(function (){
        Route::name('index')->get('/','SubjectController@index');
        Route::name('create')->post('create','SubjectController@create');
        Route::name('edit')->post('{id}/edit','SubjectController@update');
        Route::name('delete')->get('{id}/delete','SubjectController@delete');
    });
    Route::prefix('student')->name('student.')->namespace('School')->group(function (){
        Route::name('index')->get('/','StudentController@index');
        Route::name('create')->post('create','StudentController@create');
        Route::name('edit')->post('{id}/edit','StudentController@update');
        Route::name('delete')->get('{id}/delete','StudentController@delete');
        Route::name('detail')->get('{id}/detail','MarkController@detail');
        Route::name('card')->get('{id}/card','StudentController@getcard');
        Route::name('excel')->post('excel','ExcelController@getexcel');
        Route::name('search')->post('search','StudentController@search');
    });
    Route::prefix('mark')->name('mark.')->namespace('School')->group(function(){
        Route::name('index')->get('/','MarkController@index');
        Route::name('create')->post('create','MarkController@create');
        Route::name('edit')->post('{id}/edit','MarkController@update');
        Route::name('delete')->get('{id}/delete','MarkController@delete');
    });
    Route::prefix('excel')->name('excel.')->namespace('School')->group(function(){
        Route::name('downloadExcel')->post('downloadExcel', 'MaatwebsiteController@downloadExcel');
    });
    Route::prefix('pdf')->name('pdf.')->namespace('School')->group(function (){
        Route::name('downloadPdf')->post('{id}/downloadPdf','PdfController@getPdf');
    });
    Route::get('/getimages/{image}','School\StudentController@getImage');
});

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name',
        'roll_no',
        'code',
        'date_of_birth',
        'father_name',
        'mother_name',
        'town',
        'address',
        'nrc',
        'admit_date',
        'batch_id',
        'major_id',
        'year_id',
        'photo',
    ];
    public function phones(){
        return $this->hasMany('App\Models\Phone');
    }
    public function marks(){
        return $this->hasMany('App\Models\Mark');
    }
    public function years(){
        return $this->hasMany('App\Models\Year');
    }
    public function major(){
        return $this->belongsTo('App\Models\Major');
    }
}

app/Http/Controllers/School/StudentController.php
<?php

namespace App\Http\Controllers\school;

use App\Models\Batch;
use App\Models\Major;
use App\Models\Mark;
use App\Models\Phone;
use App\Models\Student;
use App\Models\Year;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class StudentController extends Controller
{
    public function index(){
        $students = Student::with('major')->paginate(8);
        $batches = Batch::all();
        $majors = Major::all();
        $years = Year::all();
        return view('student.index',compact('students','batches','majors','years'));
    }
    public function create(Request $request){
//        return $request->all();
        $validator = Validator::make($request->all(),[
            'name'=>'required|string|max:255',
            'roll_no'=>'required|string|max:255',
            'code'=>'required|string|max:255',
            'date_of_birth'=>'required|string|max:255',
            'father_name'=>'required|string|max:255',
            'mother_name'=>'required|string|max:255',
            'town'=>'required|string|max:255',
            'address'=>'required|string|max:255',
            'nrc'=>'required|string|max:255',
            'ph_no'=>'required|string|max:255',
            'admit_date'=>'required',
            'batch_id'=>'required|integer',
            'major_id'=>'required|integer',
            'year_id'=>'required|integer',
            'photo'=>'required|image',
        ]);
        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $photo = $request->file('photo');
        if (!empty($photo)) {
            $filename = uniqid() . '_' . $photo->getClientOriginalName();
            Storage::put('/uploads/' . $filename, file_get_contents($photo));
        }
        $id = DB::table('students')->insertGetId(array(
            'name'=>$request->get('name'),
            'roll_no'=>$request->get('roll_no'),
            'code'=>$request->get('code'),
            'date_of_birth'=>$request->get('date_of_birth'),
            'father_name'=>$request->get('father_name'),
            'mother_name'=>$request->get('mother_name'),
            'town'=>$request->get('town'),
            'address'=>$request->get('address'),
            'nrc'=>$request->get('nrc'),
            'admit_date'=>$request->get('admit_date'),
            'batch_id'=>$request->get('batch_id'),
            'major_id'=>$request->get('major_id'),
            'year_id'=>$request->get('year_id'),
            'photo'=>$filename,
            'created_at'=>\Carbon\Carbon::now(),
            'updated_at'=>\Carbon\Carbon::now(),
        ));

        $phones = $request->get('ph_no');
        $phone =explode(',',$phones);
        $student = Student::find($id);
        foreach ($phone as $ph){
            $student->phones()->create([
                'ph_no'=>$ph,
            ]);
        }
        return redirect()->back();
    }
    public function update(Request $request,$id){
        $validator = Validator::make($request->all(),[
            'name'=>'required|string|max:255',
            'roll_no'=>'required|string|max:255',
            'code'=>'required|string|max:255',
            'date_of_birth'=>'required|string|max:255',
            'father_name'=>'required|string|max:255',
            'mother_name'=>'required|string|max:255',
            'town'=>'required|string|max:255',
            'address'=>'required|string|max:255',
            'nrc'=>'required|string|max:255',
            'admit_date'=>'required',
            'ph_no'=>'required|string|max:255',
            'batch_id'=>'required|integer',
            'major_id'=>'required|integer',
            'year_id'=>'required|integer',
        ]);
        if($validator->fails()){
//            return $request->all();
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $student = Student::find($id);
        $student->name =$request->get('name');
        $student->roll_no = $request->get('roll_no');
        $student->code = $request->get('code');
        $student->date_of_birth = $request->get('date_of_birth');
        $student->father_name = $request->get('father_name');
        $student->mother_name=$request->get('mother_name');
        $student->town = $request->get('town');
        $student->address = $request->get('address');
        $student->nrc = $request->get('nrc');
        $student->admit_date = $request->get('admit_date');
        $student->batch_id = $request->get('batch_id');
        $student->major_id = $request->get('major_id');
        $student->year_id = $request->get('year_id');
        $file = $request->file('photo');
        $oldphoto = $student->photo;
        if(!empty($file)){
            $filename = uniqid().'_'.$file->getClientOriginalName();
            Storage::put('/uploads/'.$filename,file_get_contents($file));
            $student->photo = $filename;
            unlink(storage_path('app/uploads/'.$oldphoto));
        }
        else{
            $student->photo = $oldphoto;
        }
        $student->update();
        $phone = Phone::where('student_id',$id)->get();
        foreach($phone as $phone_arr){
            $phone_arr->delete();
        }
        $phones = $request->get('ph_no');
        $phonearr =explode(',',$phones);
        foreach ($phonearr as $ph){
            $student->phones()->create([
                'ph_no'=>$ph,
            ]);
        }
        return redirect()->back();
    }
    public function delete($id){
        $student = Student::find($id);
        $student->delete();
        $oldimage = $student->photo;
        unlink(storage_path('app/uploads/' . $oldimage));
        return redirect()->back();
    }
    public function getcard($id){
        $student = Student::find($id);
        $major_id = $student->major_id;
        $major = Major::find($major_id);
        return view('student.card',compact('student','major'));
    }
    public function getImage($name){
        return response()->file(storage_path().'/app/uploads/'.$name);
    }
    public function search(Request $request){
        $batches = Batch::all();
        $majors = Major::all();
        $years = Year::all();
        $word= $request->get('word');
        $students = Student::where('name','like','%'.$word.'%')->paginate(8);
        return view('student.index',compact('students','batches','years','majors'));
    }

}

resources/views/student/card.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{asset('css/style1.css')}}">
    <title>Document</title>
</head>
<body>
<div class="modal-card">
    <div class="modal-card-header">
        <h4 class="modal-title">SHAN COMMUNITY COLLEDGE</h4>
    </div>
    <div class="modal-card-content">
        <h2><center>STUDENT CARD</center></h2>
        <div class="student-card-data">
            <div class="card-data">
                <label>{{$major->name}}</label>
                <label>Name&emsp;&emsp;&emsp;{{$student->name}}</label>
                <label>Student ID&emsp;{{$student->code}}</label>
                <label>NRC&emsp;&emsp;&emsp;&emsp;-</label>
            </div>
            <img src="{{ URL::to('getimages/'.$student->photo) }}" width="150px" height="170px">
        </div>
    </div>
</div>
</body>
</html>

resources/views/student/detail.blade.php
@extends('masteradmin')
@section('title','Student')
@section('content')

    {{--<div class="list-of-class">--}}
        {{--<p>List of class Standard-1 Students</p>--}}
    {{--</div>--}}

    <div class="main-content">
        <div class="student-select-class">
            <label>Student Name&emsp;: {{$students->name}}</label>
            <label>Student Roll No : {{$students->roll_no}}</label>
            <label>Student Code &emsp;: {{$students->code}}</label>
        </div>

        {{--<div class="show-entries">--}}
            {{--<label>Show</label>--}}
            {{--<select>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
                {{--<option>10</option>--}}
            {{--</select>--}}
        {{--</div>--}}

        <div class="add-detail-mark">
            <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_addmark">
                <i class="fa fa-plus"></i>&nbspAdd Mark
            </button>
        </div>


        <div class="dropdown print">
            {{--<a href="{{route('pdf.downloadPdf',['id'=>$students->id])}}">--}}
                <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_pdfdata">
                    <i class="fa fa-print"></i>Transcript
                </button>
        </div>

        {{--<div class="search-box">--}}
            {{--<label>Search</label>--}}
            {{--<input class="search">--}}
        {{--</div>--}}

        <table class="table-bordered table-striped table">
            <tr>
                {{--<th><input type="checkbox"></input></th>--}}
                <th>No</th>
                <th>Year</th>
                <th>Exam</th>
                <th>Subject</th>
                <th>Mark</th>
                <th>
                    {{--<select>--}}
                        {{--<option>Select Action</option>--}}
                        {{--<option>Select</option>--}}
                        {{--<option>Select</option>--}}
                        {{--<option>Select</option>--}}
                    {{--</select>--}}
                </th>
            </tr>
            @php($no=1)
                @php($year_name='A')
                @php($exam_name='A')
                @foreach($marks as $mark)
                    <tr>
                        {{--<td><input type="checkbox"></td>--}}
                        <td>{{$no++}}</td>
                        @php($year = \App\Models\Year::find($mark->year_id))
                            @if(substr_compare($year_name,$year->name,0)==0)
                                <td></td>
                            @else
                                <td>{{$year->name}}</td>
                            @endif
                        @php($year_name=$year->name)
                        @php($exam = \App\Models\Exam::find($mark->exam_id))
                        {{--<td>{{$exam->name}}</td>--}}
                             @if(substr_compare($exam_name,$exam->name,0)==0)
                                  <td></td>
                             @else
                                  <td>{{$exam->name}}</td>
                             @endif
                        @php($exam_name=$exam->name)
                        @php($subject = \App\Models\Subject::find($mark->subject_id))
                        <td>{{$subject->name}}</td>
                        <td>{{$mark->mark}}</td>
                        <td>
                            {{--<button class="detail" data-excelurl=""><i class="fa fa-eye"></i></button>--}}
                            <button class="delete" data-toggle="modal" data-target="#modal_deletemark" data-deleteurl="{{route('mark.delete',['id'=>$mark->id])}}"><i class="fa fa-trash-o"></i></button>
                            <button class="edit" data-toggle="modal" data-target="#modal_editmark" data-year="" data-student="" data-mark="{{$mark}}" data-editurl="{{route('mark.edit',['id'=>$mark->id])}}"><i class="fa fa-pencil"></i></button>
                        </td>
                    </tr>
                @endforeach

        </table>


        <div class="page">
            {{$marks->links()}}
            {{--<ul class="pagination">--}}
            {{--<li class="page-item"><a class="page-link" href="#">Previous</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">1</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
            {{--<li class="page-item"><a class="page-link" href="#">Next</a></li>--}}
            {{--</ul>--}}
        </div>
        <div class="clearfix"></div>
    </div>
@endsection
@section('models')
    @include('mark.create_modal')
    @include('mark.edit_modal')
    @include('mark.delete_modal')
    @include('student.pdfdata_modal');
{{--    @include('mark.pdf_modal')--}}
    @endsection
@section('script')
    <script src="{{asset('js/mark.js')}}"></script>
@endsection

resources/views/student/excel_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_excel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Excel Sheet</h4>
                </div>

                <form method="post" action="{{route('excel.downloadExcel')}}">
                    {{csrf_field()}}
                    <div class="for-year">
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Year</label>
                            <select class="form-group" name="year">
                                @foreach($years as $year)
                                    <option value="{{$year->id}}">{{$year->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group modal-inside" id="name">
                            <label for="name">Major</label>
                            <select class="form-group" name="major">
                                @foreach($majors as $major)
                                    <option value="{{$major->id}}">{{$major->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/student/index.blade.php
@extends('masteradmin')
@section('title','Student')
@section('content')
        <div class="list-of-class">
            <p>List of Students</p>
        </div>

        <div class="main-content">
            {{--<div class="select-class">--}}
                {{--<label>Select Class Name</label>--}}
                {{--<select>--}}
                    {{--<option>Standard-1</option>--}}
                    {{--<option>Standard-2</option>--}}
                    {{--<option>Standard-3</option>--}}
                    {{--<option>Standard-4</option>--}}
                {{--</select>--}}
            {{--</div>--}}

            {{--<div class="show-entries">--}}
                {{--<label>Show</label>--}}
                {{--<select>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                    {{--<option>10</option>--}}
                {{--</select>--}}
            {{--</div>--}}

            <div class="add-exam">
                <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_addstudent">
                    <i class="fa fa-plus"></i>&nbspAdd Student
                </button>
            </div>


            <div class="dropdown print">
                <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_excel">
                    <i class="fa fa-print"></i>Excel
                </button>
            </div>

            <form method="post" action="{{route('student.search')}}">
                {{csrf_field()}}
            <div class="student-search-box">
                <label>Search</label>
                <input class="search" type="text" name="word">
                <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
            </div>
            </form>

            <table class="table-bordered table-striped table">
                <tr>
                    <th><input type="checkbox"></input></th>
                    <th>No</th>
                    <th>Name</th>
                    <th>Roll No</th>
                    <th>Code</th>
                    <th>
                        {{--<select>--}}
                            {{--<option>Select Action</option>--}}
                            {{--<option>Select</option>--}}
                            {{--<option>Select</option>--}}
                            {{--<option>Select</option>--}}
                        {{--</select>--}}
                    </th>
                </tr>
                @php($no=1)
                    @foreach($students as $student)
                        <tr>
                            <td><input type="checkbox"></td>
                            <td>{{$no++}}</td>
                            <td>{{$student->name}}</td>
                            <td>{{$student->roll_no}}</td>
                            <td>{{$student->code}}</td>
                            <td><a href="{{route('student.detail',['id'=>$student->id])}}"><button class="detail"><i class="fa fa-eye"></i></button></a>
                                    @php($phone = $student->phones->implode('ph_no',','))
                                <button class="delete" data-toggle="modal" data-target="#modal_deletestudent" data-phone="" data-deleteurl="{{route('student.delete',['id'=>$student->id])}}"><i class="fa fa-trash-o"></i></button>
                                <button class="edit" data-toggle="modal" data-target="#modal_editstudent" data-phone="{{$phone}}" data-student="{{$student}}" data-editurl="{{route('student.edit',['id'=>$student->id])}}"><i class="fa fa-pencil"></i></button>
                                {{--<button data-std="{{$student}}" class="delete student_card_generate" id="student_card_generate"><i class="fa fa-users"></i></button>--}}
                                <button data-std="{{$student}}" data-toggle="modal" class="delete modal_issue_expire" data-target="#modal_issue_expire"><i class="fa fa-users"></i></button>
                            </td>
                        </tr>
                    @endforeach

            </table>

            {{--<p>hi</p>--}}

            <div class="page">
                {{$students->links()}}
                {{--<ul class="pagination">--}}
                    {{--<li class="page-item"><a class="page-link" href="#">Previous</a></li>--}}
                    {{--<li class="page-item"><a class="page-link" href="#">1</a></li>--}}
                    {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
                    {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
                    {{--<li class="page-item"><a class="page-link" href="#">Next</a></li>--}}
                {{--</ul>--}}
            </div>
            <div class="clearfix"></div>

        </div>
@endsection
@section('models')
    @include('student.create_modal')
    @include('student.edit_modal')
    @include('student.delete_modal')
    @include('student.excel_modal')
    {{--Start of card-modal--}}
        <div class="modal fade" id="modal_issue_expire">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Date for Student Card</h4>
                    </div>

                        <div class="for-year">
                            <div class="form-group modal-inside" id="name">
                                <label for="name">Issue Date</label>
                                <input type="" class="datepick" id="issue_date" name="issue_date" value="{{old('issue_date')}}">
                                @if($errors->has('issue_date'))
                                    <span class="error">{{$errors->first('issue_date')}}</span>
                                @endif
                            </div>
                            <div class="form-group modal-inside" id="name">
                                <label for="name">Expiry Date</label>
                                <input type="" class="datepick" id="expire_date" name="expire_date" value="{{old('expire_date')}}">
                                @if($errors->has('expire_date'))
                                    <span class="error">{{$errors->first('expire_date')}}</span>
                                @endif
                            </div>

                            <div class="modal-save">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary student_card_generate" id="student_card_generate">Save</button>
                            </div>
                        </div>
                </div>
            </div>

        </div>

    {{--End of card-modal--}}

    <div class="modal fade" id="student_card_modal" role="dialog">
        <div>
            <div class="modal-content" id="generated_card">
                <div class="modal-card">

                    <div class="modal-card-header">
                        <img src="{{ URL::to('/') }}/logo/school_logo.png" width="50px" height="50px">
                        <h5 class="modal-title">ၸၼ့်ၸွမ်တူင်ႇၵူၼ်းတႆ</h5>
                        <h5 class="modal-title">SHAN COMMUNITY COLLEGE</h5>
                    </div>
                    <div class="modal-card-content">
                        <h4><center>STUDENT CARD</center></h4>
                        <div class="student-card-data">
                            <div class="card-data">
                                <label id="card_major_modal"></label>
                                <label>Name&emsp;&emsp;<span id="card_name_modal"></span></label>
                                <label>Student ID&emsp;<span id="card_id_modal"></span></label>
                                <label>NRC&emsp;&emsp;<span id="card_nrc_modal"></span></label>
                            </div>
                            <img id="card_image_modal" width="116px" height="125px">
                        </div>
                        <div class="card-date">
                            <label id="issue_date_label">Issued on <span id="card_issue_date_modal"></span></label>
                            <label id="expire_date_label">Expiry on <span id="card_expire_date_modal"></span></label>
                        </div>
                    </div>
                </div>
                <div class="card-logout-modal">
                <button type="button" data-dismiss="modal" class="btn btn-primary">Cancel</button>
                <a id="download"><button type="submit" class="btn btn-primary">Download</button></a>
                <div id="img-out"></div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('img')
    <div id="student_card" class="modal-card" style="background-color: white">
        <div class="modal-card-header">
            <img src="{{ URL::to('/') }}/logo/school_logo.png" width="50px" height="50px">
            <h5 class="modal-title">ၸၼ့်ၸွမ်တူင်ႇၵူၼ်းတႆ</h5>
            <h5 class="modal-title">SHAN COMMUNITY COLLEGE</h5>
        </div>
        <div class="modal-card-content">
            <h4><center>STUDENT CARD</center></h4>
            <div class="student-card-data">
                <div class="card-data">
                    <label id="card_major"></label>
                    <label>Name&emsp;&emsp;&emsp;<span id="card_name"></span></label>
                    <label>Student ID&emsp;<span id="card_id"></span></label>
                    <label>NRC&emsp;&emsp;<span id="card_nrc"></span></label>
                </div>
                <img id="card_image" width="116px" height="125px">
            </div>
            <div class="card-date">
                <label id="issue_date_label">Issued on <span id="card_issue_date"></span></label>
                <label id="expire_date_label">Expiry on <span id="card_expire_date"></span></label>
            </div>
        </div>
    </div>

    <div id="img-out"></div>
@stop
@section('script')
    <script src="{{asset('js/student.js')}}"></script>
    <script src="{{asset('js/dom2img.js')}}"></script>
    <script src="{{asset('js/html2canvas.js')}}"></script>
    <script src="{{asset('js/student-card.js')}}"></script>
@endsection