routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('adminlogin')->name('adminlogin.')->namespace('School')->group(function(){
    Route::name('index')->get('/','AdminController@showLogin');
    Route::name('login')->post('login','AdminController@login');
    Route::name('logout')->get('logout','AdminController@logout');
});

Route::group(['middleware'=>'admin'],function (){
    Route::prefix('admin')->name('admin.')->namespace('School')->group(function(){
        Route::name('index')->get('/','AdminController@index');
        Route::name('create')->post('create','AdminController@create');
        Route::name('edit')->post('{id}/edit','AdminController@update');
        Route::name('delete')->get('{id}/delete','AdminController@delete');
    });
    Route::prefix('year')->name('year.')->namespace('School')->group(function (){
        Route::name('index')->get('/','YearController@index');
        Route::name('create')->post('create','YearController@create');
        Route::name('edit')->post('{id}/edit','YearController@update');
        Route::name('delete')->get('{id}/delete','YearController@delete');
    });
    Route::prefix('batch')->name('batch.')->namespace('School')->group(function (){
        Route::name('index')->get('/','BatchController@index');
        Route::name('create')->post('create','BatchController@create');
        Route::name('edit')->post('{id}/edit','BatchController@update');
        Route::name('delete')->get('{id}/delete','BatchController@delete');
    });
    Route::prefix('major')->name('major.')->namespace('School')->group(function (){
        Route::name('index')->get('/','MajorController@index');
        Route::name('create')->post('create','MajorController@create');
        Route::name('edit')->post('{id}/edit','MajorController@update');
        Route::name('delete')->get('{id}/delete','MajorController@delete');
    });
    Route::prefix('exam')->name('exam.')->namespace('School')->group(function (){
        Route::name('index')->get('/','ExamController@index');
        Route::name('create')->post('create','ExamController@create');
        Route::name('edit')->post('{id}/edit','ExamController@update');
        Route::name('delete')->get('{id}/delete','ExamController@delete');
    });
    Route::prefix('category')->name('category.')->namespace('School')->group(function(){
        Route::name('index')->get('/','CategoryController@index');
        Route::name('create')->post('create','CategoryController@create');
        Route::name('edit')->post('{id}/edit','CategoryController@update');
        Route::name('delete')->get('{id}/delete','CategoryController@delete');
    });
    Route::prefix('subject')->name('subject.')->namespace('School')->group(function (){
        Route::name('index')->get('/','SubjectController@index');
        Route::name('create')->post('create','SubjectController@create');
        Route::name('edit')->post('{id}/edit','SubjectController@update');
        Route::name('delete')->get('{id}/delete','SubjectController@delete');
    });
    Route::prefix('student')->name('student.')->namespace('School')->group(function (){
        Route::name('index')->get('/','StudentController@index');
        Route::name('create')->post('create','StudentController@create');
        Route::name('edit')->post('{id}/edit','StudentController@update');
        Route::name('delete')->get('{id}/delete','StudentController@delete');
        Route::name('detail')->get('{id}/detail','MarkController@detail');
        Route::name('card')->get('{id}/card','StudentController@getcard');
        Route::name('excel')->post('excel','ExcelController@getexcel');
        Route::name('search')->post('search','StudentController@search');
    });
    Route::prefix('mark')->name('mark.')->namespace('School')->group(function(){
        Route::name('index')->get('/','MarkController@index');
        Route::name('create')->post('create','MarkController@create');
        Route::name('edit')->post('{id}/edit','MarkController@update');
        Route::name('delete')->get('{id}/delete','MarkController@delete');
    });
    Route::prefix('excel')->name('excel.')->namespace('School')->group(function(){
        Route::name('downloadExcel')->post('downloadExcel', 'MaatwebsiteController@downloadExcel');
    });
    Route::prefix('pdf')->name('pdf.')->namespace('School')->group(function (){
        Route::name('downloadPdf')->post('{id}/downloadPdf','PdfController@getPdf');
    });
    Route::get('/getimages/{image}','School\StudentController@getImage');
});

app/Models/Mark.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    protected $fillable = [
        'student_id',
        'subject_id',
        'exam_id',
        'year_id',
        'mark',
    ];
}

app/Http/Controllers/School/MarkController.php
<?php

namespace App\Http\Controllers\school;

use App\Models\Category;
use App\Models\Exam;
use App\Models\Mark;
use App\Models\Student;
use App\Models\Subject;
use App\Models\Year;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class MarkController extends Controller
{
    public function index(){
        $marks = Mark::all();
        $students = Student::all();
        $subjects = Subject::all();
        $exams = Exam::all();
        $categories = Category::all();
        return view('mark.index',compact('marks','students','exams','categories','subjects'));
    }
    public function create(Request $request){
        $validator = Validator::make($request->all(),[
            'year_id'=>'required',
            'subject_id'=>'required',
            'exam_id'=>'required',
            'mark'=>'required',
        ]);
        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }
//        $student=Student::where('roll_no',$request->get('searchRoll'))->first();
//        $student_id=$student->id;
//        $year = Year::where('name',$request->get('year_name'))->first();
//        $year_id = $year->id;
        Mark::create([
            'student_id'=>$request->get('student_id'),
            'subject_id'=>$request->get('subject_id'),
            'exam_id'=>$request->get('exam_id'),
            'year_id'=>$request->get('year_id'),
            'mark'=>$request->get('mark'),
        ]);
        return redirect()->back();
    }
    public function update(Request $request,$id){
        $validator = Validator::make($request->all(),[
            'student_id'=>'required',
            'subject_id'=>'required',
            'exam_id'=>'required',
            'year_id'=>'required',
            'mark'=>'required',
        ]);
        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }
        $mark = Mark::find($id);
        $mark->student_id=$request->get('student_id');
        $mark->subject_id = $request->get('subject_id');
        $mark->exam_id = $request->get('exam_id');
        $mark->year_id = $request->get('year_id');
        $mark->mark = $request->get('mark');
        $mark->update();
        return redirect()->back();
    }
    public function delete($id){
        $mark = Mark::find($id);
        $mark->delete();
        return redirect()->back();
    }
    public function detail($id){
        $students = Student::find($id);
        $years = Year::all();
        $subjects = Subject::all();
        $exams = Exam::all();
        $categories = Category::all();
//        $years = Mark::where('student_id',$students->id)->Distinct()->get(['year_id']);
        $marks = Mark::where('student_id',$students->id)->orderBy('year_id')->orderBy('exam_id')->paginate(8);
        return view('student.detail',compact('students','marks','years','subjects','exams','categories'));
    }

}

resources/views/mark/create_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_addmark">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Mark</h4>
                </div>

                <form method="post" action="{{route('mark.create')}}">
                    {{csrf_field()}}
                    <div class="for-year">
                        {{--<div class="form-group modal-inside dropdown" id="name">--}}
                            {{--<label for="name">Roll No</label>--}}
                            {{--<input type="text" class="name-input dropdown-toggle" data-toggle="dropdown" id="searchRoll" name="searchRoll" value="{{old('searchRoll')}}" autocomplete="off">--}}
                            {{--<ul class="dropdown-menu" id="roll-menu">--}}
                                {{--@foreach($students as $student)--}}
                                    {{--@php($year=\App\Models\Year::find($student->year_id))--}}
                                        {{--@php($year_name=$year->name)--}}
                                    {{--<li class="dropdown-item roll" data-year="{{$year_name}}" data-name="{{$student->name}}">{{$student->roll_no}}</li>--}}
                                {{--@endforeach--}}
                            {{--</ul>--}}
                        {{--</div>--}}

                        {{--<div class="form-group modal-inside" id="name">--}}
                            {{--<label for="student_name">Student Name</label>--}}
                            {{--<input type="text" id="student_name" class="static" name="student_name" readonly>--}}
                        {{--</div>--}}

                        {{--<div class="form-group modal-inside" id="name">--}}
                            {{--<label for="name">Year</label>--}}
                            {{--<input type="text" id="year_name" class="static" name="year_name" readonly>--}}
                        {{--</div>--}}
                        <input type="hidden" name="student_id" value="{{$students->id}}">

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Year</label>
                            <select class="form-group" name="year_id" id="year_id">
                                @foreach($years as $year)
                                    <option value="{{$year->id}}" class="{{$year->id}}">{{$year->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Exam</label>
                            <select class="form-group" name="exam_id">
                                @foreach($exams as $exam)
                                    <option value="{{$exam->id}}">{{$exam->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Subject Category</label>
                            <select class="form-group" name="category_id" id="category_id">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" class="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Subject</label>
                            <select class="form-group" name="subject_id" id="subject_id">
                                @foreach($subjects as $subject)
                                    <option value="{{$subject->id}}" class="{{$subject->category_id}}">{{$subject->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Mark</label>
                            <input type="text" class="name-input" id="mark" name="mark" value="{{old('mark')}}">
                            @if($errors->has('mark'))
                                <span class="error">{{$errors->first('mark')}}</span>
                            @endif
                        </div>

                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/mark/delete_modal.blade.php
<div class="modal fade" id="modal_deletemark" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content modal-logout">
            <div class="modal-header">
                <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Are You Sure?</h4>
            </div>
            <form id="deleteurl">
                <div class="logout-modal">
                    <!-- <div class="modal-footerdelete"> -->
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel
                    </button>
                    <button type="submit" class="btn btn-primary">Ok</button>
                    <!-- </div> -->
                </div>
            </form>
        </div>

    </div>
</div>

resources/views/mark/edit_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_editmark">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Mark</h4>
                </div>

                <form method="post" id="editurl">
                    {{csrf_field()}}
                    <div class="for-year">
                        {{--<div class="form-group modal-inside dropdown" id="name">--}}
                            {{--<label for="name">Roll No</label>--}}
                            {{--<input type="text" class="name-input dropdown-toggle" data-toggle="dropdown" id="mark_roll_no" name="searchRoll" value="{{old('searchRoll')}}" autocomplete="off">--}}
                            {{--<ul class="dropdown-menu" id="roll-edit-menu">--}}
                                {{--@foreach($students as $student)--}}
                                    {{--@php($year=\App\Models\Year::find($student->year_id))--}}
                                        {{--@php($year_name=$year->name)--}}
                                            {{--<li class="dropdown-item edit-roll" data-edit-year="{{$year_name}}" data-edit-name="{{$student->name}}">{{$student->roll_no}}</li>--}}
                                            {{--@endforeach--}}
                            {{--</ul>--}}
                        {{--</div>--}}

                        {{--<div class="form-group modal-inside" id="name">--}}
                            {{--<label for="student_name">Student</label>--}}
                            {{--<input type="text" id="mark_student_name" class="static" name="student_name" readonly>--}}
                        {{--</div>--}}

                        {{--<div class="form-group modal-inside" id="name">--}}
                            {{--<label for="name">Year</label>--}}
                            {{--<input type="text" id="mark_year" class="static" name="year_name" readonly>--}}
                        {{--</div>--}}
                        <input type="hidden" name="student_id" value="{{$students->id}}">

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Year</label>
                            <select class="form-group" name="year_id" id="mark_year_id">
                                @foreach($years as $year)
                                    <option value="{{$year->id}}" class="{{$year->id}}">{{$year->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Subject Category</label>
                            <select class="form-group" name="category_id" id="edit_category_id">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" class="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Subject</label>
                            <select class="form-group" name="subject_id" id="edit_subject_id">
                                @foreach($subjects as $subject)
                                    <option value="{{$subject->id}}" class="{{$subject->category_id}}">{{$subject->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Exam</label>
                            <select class="form-group" name="exam_id" id="mark_exam_id">
                                @foreach($exams as $exam)
                                    <option value="{{$exam->id}}">{{$exam->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Mark</label>
                            <input type="text" class="name-input" id="mark_mark" name="mark" value="{{old('mark')}}">
                            @if($errors->has('mark'))
                                <span class="error">{{$errors->first('mark')}}</span>
                            @endif
                        </div>


                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

resources/views/mark/index.blade.php
@extends('masteradmin')
@section('title','Mark')
@section('content')

    <div class="list-of-class">
        <p>List of class Standard-1 Students</p>
    </div>

    <div class="main-content">
        <div class="select-class">
            <label>Select Class Name</label>
            <select>
                <option>Standard-1</option>
                <option>Standard-2</option>
                <option>Standard-3</option>
                <option>Standard-4</option>
            </select>
        </div>

        <div class="show-entries">
            <label>Show</label>
            <select>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
                <option>10</option>
            </select>
        </div>

        <div class="add-student">
            <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#modal_addmark">
                <i class="fa fa-plus"></i>&nbspAdd Mark
            </button>
        </div>

        <div class="dropdown print">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-print"></i>Print
                <span class="caret"></span></button>
            <ul class="dropdown-menu printdropdown">
                <li><a href="{{route('excel.downloadExcel')}}">Excel</a></li>
                <li><a href="{{route('pdf.downloadPdf',['id'=>1])}}">PDF</a></li>
                <li><a href="#">A6</a></li>
            </ul>
        </div>

        <div class="search-box">
            <label>Search</label>
            <input class="search">
        </div>

        <table class="table-bordered table-striped table">
            <tr>
                <th><input type="checkbox"></input></th>
                <th>No</th>
                <th>Name</th>
                <th><select>
                        <option>Select Action</option>
                        <option>Select</option>
                        <option>Select</option>
                        <option>Select</option>
                    </select>
                </th>
            </tr>
            @php($no=1)
                @foreach($marks as $mark)
                    <tr>
                        <td><input type="checkbox"></td>
                        <td>{{$no++}}</td>
                        <td>{{$mark->student_id}}</td>
                        @php($id=$mark->student_id)
                        @php($student=\App\Models\Student::find($id))
                        @php($year=\App\Models\Year::find($student->year_id))
                        <td><button class="detail" data-excelurl=""><i class="fa fa-eye"></i></button>
                            <button class="delete" data-toggle="modal" data-target="#modal_deletemark" data-deleteurl="{{route('mark.delete',['id'=>$mark->id])}}"><i class="fa fa-trash-o"></i></button>
                            <button class="edit" data-toggle="modal" data-target="#modal_editmark" data-year="{{$year}}" data-student="{{$student}}" data-mark="{{$mark}}" data-editurl="{{route('mark.edit',['id'=>$mark->id])}}"><i class="fa fa-pencil"></i></button>
                        </td>
                    </tr>
                @endforeach

        </table>

        <p>Showing 1 to 10 of 17 entries</p>

        <div class="page">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </div>
    </div>
@endsection
@section('models')
    @include('mark.create_modal')
    @include('mark.edit_modal')
    @include('mark.delete_modal')
    @endsection
@section('script')
    <script src="{{asset('js/mark.js')}}"></script>
@endsection

resources/views/mark/pdf_modal.blade.php
<div class="add-path">
    <div class="modal fade" id="modal_pdf">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" id="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Choose For PDF</h4>
                </div>

                <form method="post" action="{{route('pdf.downloadPdf',['id'=>$students->id])}}">
                    {{csrf_field()}}
                    <div class="for-year">

                        <input type="hidden" name="student_id" value="{{$students->id}}">

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Year</label>
                            <select class="form-group" name="year_id" id="year_id">
                                <option value="0">All Years</option>
                                @foreach($years as $year)
                                    <option value="{{$year->id}}" class="{{$year->id}}">{{$year->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Exam</label>
                            <select class="form-group" name="exam_id">
                                <option value="0">All Exam</option>
                                @foreach($exams as $exam)
                                    <option value="{{$exam->id}}">{{$exam->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group modal-inside" id="name">
                            <label for="name">Subject</label>
                            <select class="form-group" name="subject_id" id="subject_id">
                                <option value="0">All Subject</option>
                                @foreach($subjects as $subject)
                                    <option value="{{$subject->id}}" class="{{$subject->category_id}}">{{$subject->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="modal-save">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>